"use client";

import { useCallback,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, Building2, CreditCard, Eye, Headphones, Pencil, Plus, Search, Settings2, ShieldAlert, Sparkles, WalletCards } from "lucide-react";
import AdminShell,{AdminTab} from "../components/AdminShell";
import StatCard from "../components/StatCard";
import TenantEditor from "../components/TenantEditor";
import BillingManager from "../components/BillingManager";
import CommercialQuotesManager from "../components/CommercialQuotesManager";
import AuditLogPanel from "../components/AuditLogPanel";
import IntegrationStatus from "../components/IntegrationStatus";
import { supabase } from "../lib/supabase";
import { ModuleKey, Subscription, Tenant, TenantSettings } from "../lib/types";
import { fallbackSettings, getTenantSettings } from "../lib/settings";

const moduleMeta:Record<ModuleKey,[string,string]>={dashboard:["Dashboard","Resumen general de la empresa"],customers:["Clientes","ABM y seguimiento de clientes"],inventory:["Inventario","Productos, precios y stock"],sales:["Ventas / POS","Operaciones de venta"],quotes:["Presupuestos","Cotizaciones a clientes"],cash:["Caja","Ingresos, egresos y cierres"],schedule:["Agenda / Turnos","Reservas y turnos"],suppliers:["Proveedores","Compras y proveedores"],employees:["Usuarios y roles","Accesos y permisos del equipo"],reports:["Reportes","Indicadores y estadísticas"]};

export default function CEODashboard(){
 const router=useRouter();const [session,setSession]=useState<any>(null);const [loading,setLoading]=useState(true);const [active,setActive]=useState<AdminTab>("dashboard");const [isAdmin,setIsAdmin]=useState(false);
 const [tenants,setTenants]=useState<Tenant[]>([]);const [subscriptions,setSubscriptions]=useState<Subscription[]>([]);const [tickets,setTickets]=useState<any[]>([]);const [settingsMap,setSettingsMap]=useState<Record<string,TenantSettings>>({});const [search,setSearch]=useState("");const [statusFilter,setStatusFilter]=useState("all");const [editor,setEditor]=useState<Tenant|null>(null);const [creating,setCreating]=useState(false);

 const load=useCallback(async()=>{setLoading(true);const [t,s,k]=await Promise.all([supabase.from("tenants").select("*").order("created_at",{ascending:false}),supabase.from("subscriptions").select("*").order("created_at",{ascending:false}),supabase.from("support_tickets").select("*").order("created_at",{ascending:false})]);if(t.error)console.error(t.error);if(s.error)console.error(s.error);if(k.error)console.error(k.error);const ts=(t.data||[]) as Tenant[];setTenants(ts);setSubscriptions((s.data||[]) as Subscription[]);setTickets(k.data||[]);const pairs=await Promise.all(ts.map(async x=>{try{return [x.id,await getTenantSettings(x.id)] as const}catch{return [x.id,fallbackSettings(x.id)] as const}}));setSettingsMap(Object.fromEntries(pairs));setLoading(false)},[]);
 const bootstrapAndLoad=useCallback(async(userId:string)=>{setLoading(true);await supabase.rpc("claim_initial_platform_admin");const {data:admin,error}=await supabase.from("platform_admins").select("user_id").eq("user_id",userId).maybeSingle();if(error||!admin){setIsAdmin(false);setLoading(false);router.replace("/portal");return}setIsAdmin(true);await load()},[load,router]);
 useEffect(()=>{let mounted=true;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!mounted)return;setSession(session);if(!session){setLoading(false);return}await bootstrapAndLoad(session.user.id)})();const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s){setLoading(false);setIsAdmin(false)}});return()=>{mounted=false;subscription.unsubscribe()}},[bootstrapAndLoad]);
 async function logout(){await supabase.auth.signOut();router.replace("/login")}

 if(loading)return <div className="grid min-h-screen place-items-center bg-slate-950"><div className="h-9 w-9 animate-spin rounded-full border-2 border-slate-700 border-t-sky-400"/></div>;
 if(!session)return <div className="grid min-h-screen place-items-center bg-slate-950 p-5 text-white"><div className="max-w-sm rounded-3xl border border-white/10 bg-white/5 p-8 text-center"><ShieldAlert className="mx-auto text-amber-400" size={42}/><h1 className="mt-4 text-xl font-black">Acceso restringido</h1><p className="mt-2 text-sm text-slate-400">Iniciá sesión para administrar ProgramFiles.</p><button onClick={()=>router.push("/login")} className="mt-6 rounded-xl bg-sky-500 px-5 py-3 text-sm font-bold">Ir al login</button></div></div>;
 if(!isAdmin)return null;

 const totalMRR=subscriptions.filter(s=>s.status!=="cancelled").reduce((a,s)=>a+Number(s.monthly_price||s.mrr||0),0);const activeCompanies=tenants.filter(t=>(settingsMap[t.id]?.status||"active")==="active").length;const openTickets=tickets.filter(t=>t.status==="open").length;const pastDue=subscriptions.filter(s=>s.status==="past_due").length;
 const filtered=tenants.filter(t=>{const text=`${t.name} ${t.slug} ${settingsMap[t.id]?.owner_name||""} ${settingsMap[t.id]?.business_type||""}`.toLowerCase();const status=settingsMap[t.id]?.status||"active";return text.includes(search.toLowerCase())&&(statusFilter==="all"||status===statusFilter)});
 const selectedSettings=editor?settingsMap[editor.id]:undefined;const selectedSubscription=editor?subscriptions.find(s=>s.tenant_id===editor.id)||null:null;

 return <AdminShell active={active} onChange={setActive} email={session.user.email} onLogout={logout}><div className="p-5 md:p-8"><div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><div className="text-xs font-black uppercase tracking-[.2em] text-sky-600">ProgramFiles / CEO</div><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-900">{title(active)}</h1><p className="mt-1 text-sm text-slate-500">{subtitle(active)}</p></div>{active==="companies"&&<button onClick={()=>setCreating(true)} className="flex items-center gap-2 rounded-xl bg-sky-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-sky-500/20 hover:bg-sky-600"><Plus size={17}/> Nueva empresa</button>}</header>

 {active==="dashboard"&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Empresas activas" value={String(activeCompanies)} note={`${tenants.length} registradas`} icon={<Building2 size={20}/>}/><StatCard label="MRR estimado" value={`$ ${totalMRR.toLocaleString("es-AR")}`} note="Ingreso recurrente" icon={<WalletCards size={20}/>}/><StatCard label="Suscripciones vencidas" value={String(pastDue)} note="Requieren seguimiento" icon={<CreditCard size={20}/>}/><StatCard label="Soporte pendiente" value={String(openTickets)} note={`${tickets.length} tickets totales`} icon={<Headphones size={20}/>}/></div><div className="mt-6 grid gap-6 xl:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-black">Empresas recientes</h2><p className="mt-1 text-xs text-slate-400">Acceso rápido a tus clientes</p></div><button onClick={()=>setActive("companies")} className="text-xs font-bold text-sky-600">Ver todas →</button></div><div className="mt-5 space-y-3">{tenants.slice(0,5).map(t=><CompanyRow key={t.id} tenant={t} settings={settingsMap[t.id]||fallbackSettings(t.id)} onEdit={()=>setEditor(t)}/>)}</div>{!tenants.length&&<div className="mt-5 rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-400">Creá tu primera empresa.</div>}</section><section className="rounded-2xl bg-slate-900 p-6 text-white"><Sparkles className="text-sky-400"/><h2 className="mt-5 text-xl font-black">ProgramFiles seguro y multiempresa</h2><p className="mt-2 text-sm leading-6 text-slate-400">RLS por empresa, roles, auditoría, logos en Storage, cobros y suspensión automática.</p><button onClick={()=>{setActive("companies");setCreating(true)}} className="mt-5 rounded-xl bg-sky-500 px-4 py-2.5 text-sm font-bold">Crear empresa</button></section></div><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 font-black"><Activity size={18} className="text-sky-600"/> Estado rápido</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Mini label="Empresas suspendidas" value={tenants.filter(t=>settingsMap[t.id]?.status==="suspended").length}/><Mini label="Empresas archivadas" value={tenants.filter(t=>settingsMap[t.id]?.status==="archived").length}/><Mini label="Links de pago listos" value={subscriptions.filter(s=>s.payment_url).length}/></div></section></>}

 {active==="companies"&&<section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 p-5 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="font-black">Empresas</h2><p className="mt-1 text-xs text-slate-400">Identidad, usuarios, módulos, estado y plan.</p></div><div className="flex flex-col gap-2 sm:flex-row"><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="all">Todos los estados</option><option value="active">Activas</option><option value="suspended">Suspendidas</option><option value="archived">Archivadas</option></select><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar empresa..." className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-4 text-sm outline-none focus:border-sky-400 sm:w-72"/></div></div></div><div className="divide-y divide-slate-100">{filtered.map(t=><CompanyRow key={t.id} tenant={t} settings={settingsMap[t.id]||fallbackSettings(t.id)} onEdit={()=>setEditor(t)}/>)}</div>{!filtered.length&&<div className="p-10 text-center text-sm text-slate-400">No hay empresas con ese filtro.</div>}</section>}

 {active==="subscriptions"&&<BillingManager subscriptions={subscriptions} tenants={tenants} settingsMap={settingsMap} onReload={load}/>} 
 {active==="quotes"&&<CommercialQuotesManager tenants={tenants}/>} 
 {active==="support"&&<SimpleTable title="Tickets de soporte" rows={tickets.map(t=>[t.subject||t.title||"Ticket",t.status||"—",t.priority||"normal",tenants.find(x=>x.id===t.tenant_id)?.name||"ProgramFiles"])} headers={["Ticket","Estado","Prioridad","Empresa"]}/>} 
 {active==="modules"&&<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-black">Catálogo de módulos</h2><p className="mt-1 text-sm text-slate-500">Se habilitan por empresa y después los roles limitan quién puede verlos o modificarlos.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(moduleMeta).map(([k,[l,d]])=><div key={k} className="rounded-xl border border-slate-200 p-4"><div className="font-bold">{l}</div><div className="mt-1 text-xs text-slate-400">{d}</div></div>)}</div></section>}
 {active==="audit"&&<AuditLogPanel tenants={tenants}/>} 
 {active==="settings"&&<div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Settings2 className="text-sky-600"/><h2 className="font-black">Integraciones y producción</h2></div><p className="mt-1 mb-5 text-sm text-slate-500">Los secretos se configuran en Vercel y nunca quedan expuestos en el navegador.</p><IntegrationStatus/></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-black">Checklist de producción</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{["RLS multiempresa activo","Service Role solo en servidor","Wildcard DNS configurado","Preview Deployment antes de Production","Backups de Supabase habilitados","Mercado Pago probado con cuenta de prueba","Certificados ARCA configurados antes de emitir","Usuarios de cliente con roles mínimos"].map(x=><div key={x} className="rounded-xl bg-slate-50 p-4 text-sm font-semibold text-slate-700">✓ {x}</div>)}</div></section></div>}
 </div></div>{(editor||creating)&&<TenantEditor tenant={editor} initialSettings={selectedSettings} initialSubscription={selectedSubscription} onClose={()=>{setEditor(null);setCreating(false)}} onSaved={load}/>}</AdminShell>
}

function CompanyRow({tenant,settings,onEdit}:{tenant:Tenant;settings:TenantSettings;onEdit:()=>void}){return <div className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className="flex min-w-0 flex-1 items-center gap-4">{settings.logo_url?<img src={settings.logo_url} alt={`Logo ${tenant.name}`} className="h-11 w-11 rounded-xl object-cover"/>:<div className="flex h-11 w-11 items-center justify-center rounded-xl text-sm font-black text-white" style={{background:settings.primary_color}}>{tenant.name.slice(0,2).toUpperCase()}</div>}<div className="min-w-0"><div className="truncate font-bold text-slate-900">{tenant.name}</div><div className="truncate text-xs text-slate-400">{settings.custom_domain||`${tenant.slug}.${process.env.NEXT_PUBLIC_ROOT_DOMAIN||"programfiles.com.ar"}`}</div></div></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${settings.status==="active"?"bg-emerald-50 text-emerald-700":settings.status==="suspended"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500"}`}>{settings.status==="active"?"Activa":settings.status==="suspended"?"Suspendida":"Archivada"}</span><div className="flex gap-2"><button onClick={()=>window.open(`/tenant/${tenant.slug}`,"_blank")} className="flex items-center gap-1.5 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50"><Eye size={15}/> Vista cliente</button><button onClick={onEdit} className="flex items-center gap-1.5 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Pencil size={14}/> Administrar</button></div></div>}
function SimpleTable({title,headers,rows}:{title:string;headers:string[];rows:any[][]}){return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5 font-black">{title}</div><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr>{headers.map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} className="p-4 text-sm text-slate-600">{String(v)}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="p-10 text-center text-sm text-slate-400">No hay registros.</div>}</div></section>}
function Mini({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-4"><div className="text-xs font-semibold text-slate-400">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
function title(a:AdminTab){return ({dashboard:"Dashboard directivo",companies:"Gestión de empresas",subscriptions:"Suscripciones y cobros",quotes:"Presupuestos comerciales",support:"Tickets de soporte",modules:"Plantillas y módulos",audit:"Auditoría y actividad",settings:"Configuración general"} as Record<AdminTab,string>)[a]}
function subtitle(a:AdminTab){return ({dashboard:"Monitoreo global de ProgramFiles.",companies:"Alta, personalización, usuarios y acceso de cada cliente.",subscriptions:"Cobros recurrentes, vencimientos y links de pago.",quotes:"Presupuestá nuevas implementaciones y personalizaciones.",support:"Seguimiento de solicitudes de clientes.",modules:"Definí las funciones que puede contratar cada empresa.",audit:"Trazabilidad de cambios sensibles.",settings:"Integraciones, seguridad y preparación de producción."} as Record<AdminTab,string>)[a]}
