"use client";
import { useEffect,useState } from "react";
import { FileText, Plus, Trash2 } from "lucide-react";
import { supabase } from "../lib/supabase";
import { Tenant } from "../lib/types";

export default function CommercialQuotesManager({tenants}:{tenants:Tenant[]}){const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState({tenant_id:"",prospect_name:"",description:"",total:"",status:"draft",valid_until:""});
 async function load(){const {data}=await supabase.from("commercial_quotes").select("*").order("created_at",{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();const {error}=await supabase.from("commercial_quotes").insert({tenant_id:form.tenant_id||null,prospect_name:form.prospect_name,description:form.description,total:Number(form.total||0),status:form.status,valid_until:form.valid_until||null});if(error)return alert(error.message);setForm({tenant_id:"",prospect_name:"",description:"",total:"",status:"draft",valid_until:""});load()}
 async function del(id:string){if(!confirm("¿Eliminar presupuesto?"))return;const {error}=await supabase.from("commercial_quotes").delete().eq("id",id);if(error)return alert(error.message);load()}
 return <div className="grid gap-6 xl:grid-cols-3"><form onSubmit={save} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2 font-black"><Plus size={18}/> Nuevo presupuesto</div><div className="mt-5 space-y-3"><Field label="Cliente / prospecto *" value={form.prospect_name} set={v=>setForm({...form,prospect_name:v})}/><div><label className="mb-1 block text-xs font-bold text-slate-500">Empresa existente (opcional)</label><select value={form.tenant_id} onChange={e=>setForm({...form,tenant_id:e.target.value})} className="w-full rounded-xl border px-3 py-2.5 text-sm"><option value="">Prospecto nuevo</option>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><Field label="Descripción" value={form.description} set={v=>setForm({...form,description:v})}/><Field label="Total" type="number" value={form.total} set={v=>setForm({...form,total:v})}/><Field label="Válido hasta" type="date" value={form.valid_until} set={v=>setForm({...form,valid_until:v})}/><button className="w-full rounded-xl bg-sky-500 py-3 text-sm font-bold text-white">Guardar presupuesto</button></div></form><section className="overflow-hidden rounded-2xl border bg-white shadow-sm xl:col-span-2"><div className="flex items-center gap-2 border-b p-5 font-black"><FileText size={18}/> Presupuestos comerciales</div><div className="divide-y">{rows.map(r=><div key={r.id} className="flex flex-col gap-3 p-4 md:flex-row md:items-center"><div className="flex-1"><div className="font-bold">{r.prospect_name}</div><div className="mt-1 text-xs text-slate-400">{r.description||"Sin descripción"}</div></div><div className="font-black">$ {Number(r.total||0).toLocaleString("es-AR")}</div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{r.status}</span><button onClick={()=>del(r.id)} className="text-slate-400 hover:text-red-500"><Trash2 size={16}/></button></div>)}{!rows.length&&<div className="p-10 text-center text-sm text-slate-400">Todavía no hay presupuestos.</div>}</div></section></div>}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div><label className="mb-1 block text-xs font-bold text-slate-500">{label}</label><input required={label.includes("*")} type={type} min={type==="number"?0:undefined} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-sm outline-none focus:border-sky-400"/></div>}
